### ISSUE TITLE
Amélioration dans SimPLU pour expérimentation IAUIDF

### ISSUE THREAD

**Issue by mbrasebin** [IGNF/simplu3D#2]
Quelques suggestions doivent être testées pour améliorer les résultats en cours :
1/ [x] Taille des bâtiments : conserver pour minimum 4m et maximum 15m  => ok

2/ [x] Forme des boîtes :  permettre que les bâtiments puissent être la résultante de l'intersection de plusieurs boîtes plutôt que d'une seule ? => en cours

3/ [x ] Forme des boîtes : est-ce que travailler avec des boîtes de forme trapézoïdales permettrait d'améliorer les propositions (notamment lorsque les parcelles présentent des angles aigus) ?

4/ [ ] Implantation des bâtiments par rapport aux limites séparatives : refuser les configurations où le bâtiment est implanté perpendiculairement à la voirie et où les baies principales donnent sur les limites séparatives latérales (les règles de distance par rapport aux limites séparatives relevées dans les PLU sont celles applicables aux façades sans baie principale).

5/ [X] Bandes de constructibilité : lorsqu'il n'y a qu'une seule bande de constructibilité, le modèle ne proposait pas la modélisation d'autres bâtiments, implantés dans la profondeur de la parcelle, au-delà du premier implanté à l'alignement

**Comment by mbrasebin** [comment]
Point 1 corrigé dans f958c08d61d437dc4cf95900b3463a9de0981a99

Le centre du cuboïde est tiré de manière à faire en sorte que la largeur maximale respecte la valeur widthmax du fichier de paramètre.

**Comment by mbrasebin** [comment]
Point 2 réglé dans 92e8dfe0db8576753293dc19309a19468cdfd37a

Ajout de 	MultipleBuildingsCuboid.ALLOW_INTERSECTING_CUBOID pour indiquer si on autorise les intersections entre boîtes.

TODO : trouver les bons paramètres pour "ponderation_volume_inter"

**Comment by mbrasebin** [comment]
Point 5 corrigé dans da87407059e09d4ab7fb7df55c8f8463dd4c9ac5

S'il n'y a qu'une seule bande et qu'un alignement est nécessaire, il ajout des cuboids "simpleCuboid" en première bande en plus des ParallelCuboid (à une distance supérieure à maxwid)

**Comment by mbrasebin** [comment]
Point 4 modifié dans d05ba2a703b36fb03db0caf9bc93d6d33a0031b4 

Attention : expérimental et à tester, s'active en settant Exec_EPFIF.USE_DEMO_SAMPLER a true.

Des objets trapezoides s'appliquent dans la première bande de constructibilité.

Les dimensions des objets ne sont pas parfaitement contrôlés.

**Comment by ilokhat** [comment]
Trapezoid à débugger imu 77049072 à tester

**Comment by mbrasebin** [comment]
Corrected in 0aa8d2b
